[Application]
Port = 8080
BaseURL = "http://localhost:4321"
BasePath = "/"
SiteDefaultLang = "en"
SiteTitle = "Nordic Control Panel"
DatabaseURL = "mysql://user:password@localhost/nordic"

[Security]
AllowedDomains = [{ protocol = "https", hostname = "mysite.com" }]

# ------ Authentication
# A secret value used for encryption and hashing.
# It must be at least 32 characters and generated
# with high entropy.
# You can use openssl rand -base64 32 to generate one.
[Authentication]
Secret = "32charsecret"

[Email]
# ------ Email settings
Enabled = false
# Below values are unused if previous value is not enabled
FromAddress = "noreply@domain"
FromName = "Mailer"
SMTPHost = "host"
SMTPPassword = "password"
SMTPPort = 587

[Athena]
DatabaseURL = "mysql://user:password@localhost/rathena"
ServerName = "MyRoServer"
# This setting correlates the minimum db login.group_id with the internal role system
Levels = { 0 = "Normal", 2 = "Support", 10 = "GM", 99 = "Admin" }

[Athena.Servers]
Char = { host = "localhost", port = 6121 }
Login = { host = "localhost", port = 6900 }
Map = { host = "localhost", port = 5121 }
